apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-helm
    server: https://kubernetes.default.svc
  project: default
  source: # this is ok because it finds kustomization.yaml
    plugin:
      name: kustomize-helm
      env:
        - name: RELEASE_STAGE # this becomes ARGOCD_ENV_RELEASE_STAGE
          value: "production"
      parameters:
        - name: "replica_count"
          value: "5"
        - name: "environment"
          value: "prod"
    path: ch11/configmanagementplugins
    repoURL: https://github.com/javacoder720/argocd-up-and-running-book
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
