apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-helm-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-helm
    spec:
      generate:
        args: 
          - "/bin/sh"
          - "-c"
          - |
            PARMS="replica_count=${ARGOCD_APP_PARAMETER_replica_count}, environment=${ARGOCD_APP_PARAMETER_environment}"
            kustomize build --enable-helm | \
            sed "s/PLACEHOLDER_ENV/${ARGOCD_ENV_RELEASE_STAGE}/g" | \
            sed "s/PLACEHOLDER_PARAMS/${PARMS}/g"

