mariadb:
  architecture: "standalone"
  auth:
    database: "golist"
    username: "golist"
    password: "golist"
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
    tag: "10.6"
